### ISSUE TITLE
FlowSaga Tutorial: Error at Deploying flight-book to app: travel

### ISSUE THREAD

**Issue by bellrauthien** [fnproject/tutorials#123]
There is an error when trying to deploy **flight-book.**

Seems like **jdk9-1.0.73** tag does not exist for **fn-java-fdk-build** image.

Here is the error message:

```
Current Context:  default
Sending build context to Docker daemon  84.48kB
Step 1/11 : FROM fnproject/fn-java-fdk-build:jdk9-1.0.73 as build-stage
manifest for fnproject/fn-java-fdk-build:jdk9-1.0.73 not found

Fn: deploy error on /u01/app/fn/tutorials/FlowSaga/flight/book/func.yaml: error running docker build: exit status 1
```

Looking at DockerHub > fnproject/fn-java-fdk-build, *there is no jdk9-1.0.73 tag*. The latest one is *jdk9-1.0.72.*

**Comment by zootalures** [comment]
Thanks, it looks like something broke in the last deploy, I’m investigating now

**Comment by zootalures** [comment]
I’ve had to roll back the broken 1.0.73 release, can you try again now, thanks

**Comment by bellrauthien** [comment]
It worked now. Thanks for your time and help.

With the new version of Fn Server, I think this command structure should change as well:

```
root@spsapigateway:/u01/app/fn/tutorials/FlowSaga# fn list routes travel

Fn: 'routes' is not a Fn Command

See 'fn <command> --help' for more information. Note the fn CLI command structure has changed, please change your command to use the new structure.
```

**Comment by rcarrascosps** [comment]
Hi. I managed to deploy everything and update the commands for the latest version of Fn, but when I call the functions I am getting this error:
root@spsapigateway:~/demo/tutorials/FlowSaga# fn get logs travel trip 01CT9DQNMXNG8G00GZJ000014Q
Exception in thread "main" java.lang.NoSuchMethodError: com.fnproject.fn.api.OutputEvent.fromBytes([BLcom/fnproject/fn/api/OutputEvent$Status;Ljava/lang/String;)Lcom/fnproject/fn/api/OutputEvent;
        at com.fnproject.fn.runtime.exception.InternalFunctionInvocationException.<init>(InternalFunctionInvocationException.java:22)
        at com.fnproject.fn.runtime.MethodFunctionInvoker.tryInvoke(MethodFunctionInvoker.java:39)
        at com.fnproject.fn.runtime.FunctionRuntimeContext.tryInvoke(FunctionRuntimeContext.java:180)
        at com.fnproject.fn.runtime.EntryPoint.lambda$run$0(EntryPoint.java:98)
        at com.fnproject.fn.runtime.HttpEventCodec.runCodec(HttpEventCodec.java:178)
        at com.fnproject.fn.runtime.EntryPoint.run(EntryPoint.java:94)
        at com.fnproject.fn.runtime.EntryPoint.main(EntryPoint.java:43)


Any ideas?

**Comment by denismakogon** [comment]
@rcarrascosps maybe because flow lib API changed, no? Which version of Java FDK do you use?
